import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={`${styles.navbar}`}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/blog">
            <li>Blog</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>
      <main className={`${styles.main}`}>
        <h1 className={`${styles.title}`}>Huncting Coder</h1>
        <p>A blog for hunting coders by a hunting coder</p>
        <div className={`${styles.blog}`}>
          <div className={`${styles.blogItem}`}>
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic website</p>
          </div>
          <div className={`${styles.blogItem}`}>
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic website</p>
          </div>
          <div className={`${styles.blogItem}`}>
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic website</p>
          </div>
        </div>
      </main>
    </>
  );
}
