import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
            margin-bottom: 20px;
          }
          h3 {
            margin-bottom: 20px;
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Code Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1 className={`${styles.title}`}>Huncting Coder</h1>
        <Image
          className={`${styles.myImg}`}
          src="/hunterHome.avif"
          alt="hunterHome"
          width={237}
          height={158}
        />
        <p>A blog for hunting coders by a hunting coder</p>
        <div className={`${styles.container}`}>
          <h2>Popular Blogs</h2>
          <div className={`${styles.blogItem}`}>
            <Link href={`/blogpost/learn-javascript`}>
              <h3>How to learn Javascript in 2023?</h3>
            </Link>
            <p>Javascript is the language used to design logic website</p>
          </div>
          <div className={`${styles.blogItem}`}>
            <Link href={`/blogpost/learn-javascript`}>
              <h3>How to learn ReactJs in 2023?</h3>
            </Link>
            <p>Javascript is the language used to design logic website</p>
          </div>
          <div className={`${styles.blogItem}`}>
            <Link href={`/blogpost/learn-javascript`}>
              <h3>How to learn NextJs in 2023?</h3>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
